/*
# Create AI Consultations and Business Scans Tables

## Purpose
Stores AI-powered consultation reports and business scanner results generated by the AI Assistant and Business Scanner components on the homepage.

## New Tables

### 1. `ai_consultations`
Stores the full AI consultation conversation results — business type, selected services, budget, timeline, audience, country, features, and the generated proposal data (pricing, scores, roadmap).

- `id` (uuid, primary key)
- `business_type` (text) — e.g. "Restaurant", "Startup"
- `service_needed` (text) — e.g. "Website", "App"
- `budget` (text) — selected budget range
- `timeline` (text) — selected timeline
- `audience` (text) — target audience
- `country` (text) — target country
- `features` (text[]) — selected features
- `base_price` (integer) — base service price
- `gst` (integer) — GST amount
- `total_price` (integer) — total including GST
- `success_score` (integer) — AI-calculated success score (0-100)
- `growth_prediction` (integer) — estimated growth percentage
- `overall_digital_score` (integer) — current digital presence score (0-100)
- `potential_score` (integer) — potential score after Digi 8 (0-100)
- `digital_scores` (jsonb) — breakdown of digital presence scores
- `roadmap` (jsonb) — project roadmap phases
- `technologies` (text[]) — recommended technologies
- `lead_id` (uuid) — optional link to leads table
- `created_at` (timestamptz)

### 2. `business_scans`
Stores AI Business Scanner results — the input (business name/URL), all 11 scanned metrics, AI score, and recommendations.

- `id` (uuid, primary key)
- `input` (text) — business name or URL scanned
- `website_speed` (integer) — speed score (0-100)
- `seo` (integer) — SEO score
- `branding` (integer) — branding score
- `security` (integer) — security score
- `performance` (integer) — performance score
- `google_presence` (integer) — Google presence score
- `social_media` (integer) — social media score
- `marketing` (integer) — marketing score
- `trust_score` (integer) — trust score
- `mobile_optimization` (integer) — mobile optimization score
- `accessibility` (integer) — accessibility score
- `ai_score` (integer) — overall AI score (average of all metrics)
- `recommendations` (text[]) — AI-generated recommendations
- `lead_id` (uuid) — optional link to leads table
- `created_at` (timestamptz)

## Security
- Both tables are single-tenant (no sign-in required for visitors using the AI tools).
- RLS enabled on both tables.
- Anon + authenticated can INSERT (visitors submit consultations/scans).
- Authenticated (admin) can SELECT, UPDATE, DELETE.
- No anon SELECT — admin views results through the admin panel.

## Notes
1. The `leads` table already exists from a prior migration and stores basic lead info.
2. These tables store the detailed AI-generated data linked to leads via `lead_id`.
3. All scores are integers 0-100.
4. `digital_scores` and `roadmap` use JSONB for flexible structured storage.
*/

-- AI Consultations table
CREATE TABLE IF NOT EXISTS ai_consultations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_type text,
  service_needed text,
  budget text,
  timeline text,
  audience text,
  country text,
  features text[] DEFAULT '{}',
  base_price integer DEFAULT 0,
  gst integer DEFAULT 0,
  total_price integer DEFAULT 0,
  success_score integer DEFAULT 0,
  growth_prediction integer DEFAULT 0,
  overall_digital_score integer DEFAULT 0,
  potential_score integer DEFAULT 0,
  digital_scores jsonb DEFAULT '{}',
  roadmap jsonb DEFAULT '[]',
  technologies text[] DEFAULT '{}',
  lead_id uuid REFERENCES leads(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE ai_consultations ENABLE ROW LEVEL SECURITY;

-- Allow anon + authenticated to INSERT (visitors submit consultations)
DROP POLICY IF EXISTS "anon_insert_ai_consultations" ON ai_consultations;
CREATE POLICY "anon_insert_ai_consultations" ON ai_consultations FOR INSERT
  TO anon, authenticated WITH CHECK (true);

-- Allow authenticated (admin) to SELECT
DROP POLICY IF EXISTS "auth_select_ai_consultations" ON ai_consultations;
CREATE POLICY "auth_select_ai_consultations" ON ai_consultations FOR SELECT
  TO authenticated USING (true);

-- Allow authenticated (admin) to UPDATE
DROP POLICY IF EXISTS "auth_update_ai_consultations" ON ai_consultations;
CREATE POLICY "auth_update_ai_consultations" ON ai_consultations FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

-- Allow authenticated (admin) to DELETE
DROP POLICY IF EXISTS "auth_delete_ai_consultations" ON ai_consultations;
CREATE POLICY "auth_delete_ai_consultations" ON ai_consultations FOR DELETE
  TO authenticated USING (true);

-- Business Scans table
CREATE TABLE IF NOT EXISTS business_scans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  input text NOT NULL,
  website_speed integer DEFAULT 0,
  seo integer DEFAULT 0,
  branding integer DEFAULT 0,
  security integer DEFAULT 0,
  performance integer DEFAULT 0,
  google_presence integer DEFAULT 0,
  social_media integer DEFAULT 0,
  marketing integer DEFAULT 0,
  trust_score integer DEFAULT 0,
  mobile_optimization integer DEFAULT 0,
  accessibility integer DEFAULT 0,
  ai_score integer DEFAULT 0,
  recommendations text[] DEFAULT '{}',
  lead_id uuid REFERENCES leads(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE business_scans ENABLE ROW LEVEL SECURITY;

-- Allow anon + authenticated to INSERT (visitors submit scans)
DROP POLICY IF EXISTS "anon_insert_business_scans" ON business_scans;
CREATE POLICY "anon_insert_business_scans" ON business_scans FOR INSERT
  TO anon, authenticated WITH CHECK (true);

-- Allow authenticated (admin) to SELECT
DROP POLICY IF EXISTS "auth_select_business_scans" ON business_scans;
CREATE POLICY "auth_select_business_scans" ON business_scans FOR SELECT
  TO authenticated USING (true);

-- Allow authenticated (admin) to UPDATE
DROP POLICY IF EXISTS "auth_update_business_scans" ON business_scans;
CREATE POLICY "auth_update_business_scans" ON business_scans FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

-- Allow authenticated (admin) to DELETE
DROP POLICY IF EXISTS "auth_delete_business_scans" ON business_scans;
CREATE POLICY "auth_delete_business_scans" ON business_scans FOR DELETE
  TO authenticated USING (true);

-- Indexes for admin panel queries
CREATE INDEX IF NOT EXISTS idx_ai_consultations_created_at ON ai_consultations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_consultations_lead_id ON ai_consultations(lead_id);
CREATE INDEX IF NOT EXISTS idx_business_scans_created_at ON business_scans(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_business_scans_lead_id ON business_scans(lead_id);
